# Generated by Django 4.1.7 on 2023-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexcal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategypositiondup',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
