# Generated by Django 4.0.4 on 2023-05-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexcal', '0002_optionstrategypositiondup_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrategypositiondup',
            name='buysell',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
    ]
