# Generated by Django 4.0.4 on 2023-05-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexcal', '0003_alter_optionstrategypositiondup_buysell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrategydup',
            name='days_from_today',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
